### ISSUE TITLE
to_string fails for some reason

### ISSUE THREAD

**Issue by alex88** [joshnuss/xml_builder#14]
I've this xml structure

```
{"SOAP-ENV:Envelope", %{"xlmns:SOAP-ENV" => "http://schemas.xmlsoap.org/soap/envelope/", "xmlns:ns1" => "url"},
  [
    {"SOAP-ENV:Header", nil,
      {"ns1:UserCredentials", nil,"test"}
    }
  ]
}
|> XmlBuilder.generate
```

this gives

```
     ** (Protocol.UndefinedError) protocol String.Chars not implemented for {"ns1:UserCredentials", nil, "test"}
     stacktrace:
       (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
       (elixir) lib/string/chars.ex:17: String.Chars.to_string/1
       lib/xml_builder.ex:122: XmlBuilder.escape/1
       lib/xml_builder.ex:75: XmlBuilder.generate/2
       (elixir) lib/enum.ex:1215: anonymous fn/4 in Enum.map_join/3
       (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
       (elixir) lib/enum.ex:1214: Enum.map_join/3
       lib/xml_builder.ex:90: XmlBuilder.generate_content/2
       lib/xml_builder.ex:84: XmlBuilder.generate/2
       (project_connector) lib/project/client.ex:20: Project.Client.call/2
       (project_connector) lib/project/client.ex:5: Project.Client.get_teams/0
       test/project/client_test.exs:10: (test)
```

if I replace the userCredentials instead it works fine, why?

```
{"SOAP-ENV:Envelope", %{"xlmns:SOAP-ENV" => "http://schemas.xmlsoap.org/soap/envelope/", "xmlns:ns1" => "test"},
  [
    {"SOAP-ENV:Header", nil, "test"
    }
  ]
}
|> XmlBuilder.generate
```

is there a nesting limit?

**Comment by joshnuss** [comment]
I think it's because the `ns1:UserCredentials` is not wrapped in an array.

Also, it might be cleaner to use `element`, as you wont need to specify `nil` when you dont use attributes.
For example:

```elixir
import XmlBuilder

doc = element("SOAP-ENV:Envelope", %{"xlmns:SOAP-ENV" => "http://schemas.xmlsoap.org/soap/envelope/", "xmlns:ns1" => "url"},
        [element("SOAP-ENV:Header", [
           element("ns1:UserCredentials", "test")
       ])
])

doc |> generate |> IO.puts
```

**Comment by joshnuss** [comment]
I'm considering removing the need to specify an array when there is just one child element.

for example. allowing:

`element(:name, element(:child, value))`

instead of:

`element(:name, [element(:child, value)])`

**Comment by alex88** [comment]
Yeah that would be great, anyway wrapping it in an array works, thank you!
